import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Foo from '../components/foo/Foo';

import styles from '../styles/Home.module.css'
import Star from '../icons/star.svg';

export default function Home() {
  const [ apiData, setApiData ] = useState({});

  
  const getData = () => {
    fetch('/api/users')
      .then(response => response.json())
      .then(data => setApiData(data))
    ;
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">NameBook!</a>
        </h1>

        <p className={styles.description}>
          The Facebook powered name flashcard site
        </p>

        <div className={styles.grid}>
          <a onClick={getData} className={styles.card}>
            <h2>Get Friends list &rarr;</h2>
          </a>
        </div>
        <button>Get Data</button>
        <pre className={styles.code}><code>
          {JSON.stringify(apiData, null, 2)}
        </code></pre>
        <Foo/>
        <Star/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
